// Creates .env with a freshly generated database password.
// Never prints secret values, and never overwrites an existing .env.
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const envPath = resolve(process.cwd(), ".env");

if (existsSync(envPath)) {
  console.log(".env already exists - left unchanged.");
  process.exit(0);
}

const password = randomBytes(24).toString("hex");
const port = 5433;

const content = [
  "# Generated by pnpm env:init. Do not commit this file.",
  `POSTGRES_PASSWORD=${password}`,
  `POSTGRES_PORT=${port}`,
  `DATABASE_URL=postgres://crm:${password}@localhost:${port}/crm`,
  "",
].join("\n");

writeFileSync(envPath, content, { mode: 0o600 });
console.log(".env created with a random database password (value not shown).");
